services:
  paragoniks-api:
    container_name: ${DOCKER_API_CONTAINER_NAME}
    command: pnpm run dev
    depends_on:
      - paragoniks-db
      - paragoniks-bucket
    restart: unless-stopped
    build:
      context: ./api/docker
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./api:/usr/src/app
      - ./data/uploads:/usr/src/app/uploads
    env_file:
      - ".env"
      - "./api/.env"
    ports: 
      - 3000:3000

  paragoniks-db:
    container_name: ${DOCKER_DB_CONTAINER_NAME}
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD}
    ports:
      - 27017:27017

  paragoniks-bucket:
    container_name: paragoniks-bucket
    image: fsouza/fake-gcs-server
    command:
      - -scheme
      - http
      - -port
      - "4443"
      - -external-url
      - http://paragoniks-bucket:4443
    ports:
      - "4443:4443"
    volumes:
      - paragoniks-storage:/data

volumes:
  paragoniks-storage:
