services:
  paragoniks-api:
    container_name: ${DOCKER_API_CONTAINER_NAME}
    command: pnpm run dev
    depends_on:
      - paragoniks-db
      - paragoniks-bucket
      - paragoniks-pubsub
    restart: unless-stopped
    build:
      context: ./api/docker
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./api:/usr/src/app
    env_file:
      - ".env"
      - "./api/.env"
    ports: 
      - 3000:3000

  paragoniks-db:
    container_name: ${DOCKER_DB_CONTAINER_NAME}
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD}
    volumes:
      - paragoniks-mongo:/data
    ports:
      - 27017:27017

  paragoniks-bucket:
    container_name: paragoniks-bucket
    image: fsouza/fake-gcs-server
    command:
      - -scheme
      - http
      - -port
      - "4443"
      - -external-url
      - http://paragoniks-bucket:4443
    ports:
      - "4443:4443"
    volumes:
      - paragoniks-bucket:/data

  paragoniks-pubsub:
    container_name: paragoniks-pubsub
    image: google/cloud-sdk:emulators
    ports:
      - 8432:8432
    command: gcloud beta emulators pubsub start --host-port=paragoniks-pubsub:8432
    volumes:
      - paragoniks-pubsub:/data

  receipt-scanner:
    container_name: receipt-scanner
    build:
      context: ./receipt-scanner
      dockerfile: docker/Dockerfile
    depends_on:
      - paragoniks-db
      - paragoniks-pubsub
    volumes:
      - ./receipt-scanner:/usr/src/app
    env_file:
      - ".env"
      - "./receipt-scanner/.env"
    command: pnpm dev

volumes:
  paragoniks-bucket:
  paragoniks-mongo:
  paragoniks-pubsub:
