export * as userAnonimsController from './anonimUsers.controller'
export * as authController from './auth.controller'
export * as friendController from './friend.controller'
export * as receiptController from './receipt.controller'
export * as scanCountController from './scanCount.controller'
export * as statusController from './status.controller'
export * as userController from './user.controller'
