export * as userAnonimsController from './anonimUsers.controller'
export * as authController from './auth.controller'
export * as friendController from './friend.controller'
export * as receiptController from './receipt.controller'
export * as userController from './user.controller'
