export * as friendsService from './endpoints/friends/friends.api'
export * as profilesService from './endpoints/profiles/profiles.api'
export * as receiptService from './endpoints/receipt/receipt.api'
export * as userService from './endpoints/user/user.api'
export { getRsApi } from './rs.api'
