name: Backend

on:
  workflow_run:
    workflows: [ESLint Check]
    types: 
      - completed
    
jobs:
  build-backend:
    runs-on: ubuntu-latest
    name: Build Backend
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./api
          file: ./api/docker/Dockerfile
          target: production
          tags: zlskey/paragoniks-api:latest
          build-args: |
            NODE_ENV=${{ vars.NODE_ENV }}
            PORT=${{ vars.PORT }}
            CORS_ORIGIN=${{ vars.CORS_ORIGIN }}
          secrets: |
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            MONGODB_URL=${{ secrets.MONGODB_URL }}
            MONGODB_ROOT_USERNAME=${{ secrets.MONGODB_ROOT_USERNAME }}
            MONGODB_ROOT_PASSWORD=${{ secrets.MONGODB_ROOT_PASSWORD }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          push: true
  deploy-backend:
    runs-on: ubuntu-latest
    name: Deploy Backend
    needs: build-backend
    steps:
      - name: ssh-job
        # You may pin to the exact commit or the version.
        # uses: nekiro/ssh-job@e0d177751aced5bcaf110ce4d782a681e5e12856
        uses: nekiro/ssh-job@v1.0.5
        with:
          host: 192.109.241.187
          port: 420
          key: ${{ secrets.PARAGONIKS_DEPLOYER_RSA_KEY }}
          user: paragoniks-deployer
          command: |
            cd /home/projects/roommate-shopper
            git pull
            make pull-images
            make start-production
    
    
