name: Eslint check
on: push
  # push:
  #   branches:
  #     - main

jobs:
  eslint-check-frontend:
    runs-on: ubuntu-latest
    container:
      image: node:20.10.0
      env:
        NODE_ENV: development
      options: --cpus 1
    steps:
      - uses: actions/checkout@main
      - run: cd app
      - run: pnpm ci
      - run: pnpm lint
      - run: cd ../api
      - run: pnpm ci
      - run: pnpm lint
      
