name: Eslint check

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.10]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Run commands in frontend dir
        run: |
          cd app
          pnpm ci
          pnpm lint
      - name: Move to backend dir
        run: cd ../api
      - name: Install deps
        run: pnpm ci
      - name: ESlint check
        run: pnpm lint
