name: Super Workflow

on:
  push:
    branches:
      - main
      - check
    paths:
      - 'app/**'
      - 'api/**'
      - 'infrastructure/**'

jobs:
  eslint:
    runs-on: ubuntu-22.04
    name: ESLint
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Run ESLint check for frontend
        run: |
          pnpm install --frozen-lockfile
          pnpm lint
        working-directory: ./app
      - name: Run ESLint check for backend
        run: |
          pnpm install --frozen-lockfile
          pnpm lint
        working-directory: ./api

  terraform:
    runs-on: ubuntu-latest
    name: Apply Terraform
    if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'infrastructure/')
    needs: [eslint, build-backend]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.0.0"
          
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: paragoniks-455316
          
      - name: Terraform Init
        run: |
          cd infrastructure
          terraform init
          
      - name: Terraform Plan
        run: |
          cd infrastructure
          terraform plan
          
      - name: Terraform Apply
        run: |
          cd infrastructure
          terraform apply -auto-approve

  build-backend:
    runs-on: ubuntu-latest
    name: Build Backend
    if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'api/')
    needs: [eslint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: paragoniks-455316
          
      - name: Configure Docker for GCP Artifact Registry
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev
          
      - name: Declare commit hash variable
        shell: bash
        run: echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        run: |
          docker build -t europe-west3-docker.pkg.dev/paragoniks-455316/paragoniks-api/paragoniks-api:${{ env.sha_short }} \
                     -t europe-west3-docker.pkg.dev/paragoniks-455316/paragoniks-api/paragoniks-api:latest \
                     -f ./api/docker/Dockerfile ./api
          
          docker push europe-west3-docker.pkg.dev/paragoniks-455316/paragoniks-api/paragoniks-api:${{ env.sha_short }}
          docker push europe-west3-docker.pkg.dev/paragoniks-455316/paragoniks-api/paragoniks-api:latest
